name: Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"  # Make sure this matches your local Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Clean previous coverage data
        run: rm -f .coverage*

      - name: Run tests with coverage
        run: |
          pytest --cov=API_Testing --cov=UI_Testing --cov-report=term-missing

      - name: Generate HTML coverage report (optional)
        run: |
          coverage html
        continue-on-error: true

      - name: Upload HTML coverage report as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
